# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
 Default

steps:
- task: UiPathPack@4
  inputs:
    versionType: 'AutoVersion'
    projectJsonPath: '$(Build.SourcesDirectory)'
    outputType: 'Process'
    orchestratorConnection: 'TSILTSC15022024'
    outputPath: '$(Build.ArtifactStagingDirectory)\Output'
- task: UiPathTest@4
  inputs:
    testTarget: 'TestProject'
    orchestratorConnection: 'TSILTSC15022024'
    folderName: 'Meera'
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'Demo15022024'
    publishLocation: 'Container'
